# spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-vue-admin?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456


# mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml